import { Link } from "@tanstack/react-router";
import { BotIcon, ChevronDownIcon, ChevronUpIcon, PencilIcon } from "lucide-react";
import { formatMoney, formatDateTime, shortId } from "@/lib/formatters";

export type JournalCardEntry = {
  id: string;
  workspaceId?: string | null;
  decisionId?: string | null;
  paperTradeId?: string | null;
  mood?: string | null;
  disciplineScore?: number | null;
  notes?: string | null;
  createdAt?: string | null;
};

export type JournalCardTrade = {
  id?: string;
  direction?: string;
  asset?: string;
  entryPrice?: number;
  exitPrice?: number;
  positionSize?: number;
  pnl?: number;
  pnlPercent?: number;
  status?: string;
};

export function JournalEntryCard({
  entry,
  trade,
  workspaceName,
  expanded,
  onToggle,
}: {
  entry: JournalCardEntry;
  trade?: JournalCardTrade;
  workspaceName: string;
  expanded: boolean;
  onToggle: () => void;
}) {
  const dimensions = parseDimensions(entry.notes);
  const emotion = entry.mood || dimensions.emotion.label || "Neutral";
  const confidence = dimensions.reasoning.confidence || "B";
  const pnl = Number(trade?.pnl ?? dimensions.trade.pnl ?? 0);
  const outcome = trade?.status === "open" || !Number.isFinite(pnl) ? "open" : pnl > 0 ? "win" : pnl < 0 ? "loss" : "open";
  const autoGenerated = Boolean(entry.paperTradeId || dimensions.trade.source === "paper.trade.lifecycle");

  return (
    <article className="rounded-lg border bg-card/70 p-4 backdrop-blur-xl">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="min-w-0">
          <div className="flex flex-wrap items-center gap-2 text-sm">
            <span className={`size-2 rounded-full ${outcome === "win" ? "bg-emerald-300" : outcome === "loss" ? "bg-red-300" : "bg-muted-foreground"}`} />
            <span className="font-medium">{formatDateTime(entry.createdAt)}</span>
            {entry.workspaceId ? (
              <Link className="rounded border border-cyan-400/25 bg-cyan-400/10 px-2 py-1 text-xs text-cyan-100 hover:border-cyan-300" params={{ workspaceId: entry.workspaceId }} to="/workspace/$workspaceId">
                {workspaceName}
              </Link>
            ) : (
              <span className="rounded border border-white/10 px-2 py-1 text-xs text-muted-foreground">Global</span>
            )}
            <span className="inline-flex items-center gap-1 rounded border border-white/10 px-2 py-1 text-xs text-muted-foreground">
              {autoGenerated ? <BotIcon className="size-3" /> : <PencilIcon className="size-3" />}
              {autoGenerated ? "Auto" : "Manual"}
            </span>
          </div>
          <TradeLine dimensions={dimensions} pnl={pnl} trade={trade} />
        </div>
        <div className="flex flex-wrap items-center justify-end gap-2">
          <EmotionChip label={emotion} />
          <ConfidenceBadge value={confidence} />
        </div>
      </div>

      <p className="mt-3 line-clamp-2 text-sm text-muted-foreground">{dimensions.reasoning.preview || plainPreview(entry.notes) || "No reasoning recorded."}</p>
      {dimensions.reflection.preview && <p className="mt-2 line-clamp-1 text-xs text-muted-foreground">Reflection: {dimensions.reflection.preview}</p>}

      <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-3">
        <button className="inline-flex items-center gap-1 text-sm text-cyan-200 hover:text-cyan-100" onClick={onToggle} type="button">
          {expanded ? "Collapse Detail" : "Expand Full Detail"}
          {expanded ? <ChevronUpIcon className="size-4" /> : <ChevronDownIcon className="size-4" />}
        </button>
        <div className="flex flex-wrap gap-2 text-xs text-muted-foreground">
          {entry.decisionId && <span className="rounded border border-white/10 px-2 py-1">Linked: {shortId(entry.decisionId)}</span>}
          {entry.paperTradeId && <span className="rounded border border-white/10 px-2 py-1">Trade: {shortId(entry.paperTradeId)}</span>}
        </div>
      </div>

      {expanded && (
        <div className="mt-4 grid gap-3 lg:grid-cols-2">
          <DimensionBox title="1. Trade Data" value={dimensions.trade.detail || tradeDetail(trade, pnl)} />
          <DimensionBox title="2. Reasoning" value={dimensions.reasoning.detail || plainPreview(entry.notes) || "No reasoning captured."} />
          <section className="rounded-md border border-white/10 p-3">
            <div className="mb-2 text-xs uppercase tracking-wide text-muted-foreground">3. Emotion</div>
            <div className="flex flex-wrap items-center gap-2">
              <EmotionChip label={emotion} />
              <span className="text-sm text-muted-foreground">Discipline {entry.disciplineScore ?? 0}/100</span>
            </div>
            <PressureBar value={dimensions.emotion.pressure ?? pressureFromDiscipline(entry.disciplineScore)} />
          </section>
          <DimensionBox title="4. Reflection" value={dimensions.reflection.detail || "No post-trade reflection yet."} />
        </div>
      )}
    </article>
  );
}

function TradeLine({ trade, dimensions, pnl }: { trade?: JournalCardTrade; dimensions: ReturnType<typeof parseDimensions>; pnl: number }) {
  const direction = trade?.direction ?? dimensions.trade.direction ?? "NOTE";
  const asset = trade?.asset ?? dimensions.trade.asset ?? "Journal";
  const size = trade?.positionSize ?? dimensions.trade.positionSize ?? 0;
  const entry = trade?.entryPrice ?? dimensions.trade.entryPrice;
  const exit = trade?.exitPrice ?? dimensions.trade.exitPrice;
  return (
    <div className="mt-3 flex flex-wrap items-center gap-2 text-sm">
      <span className={`rounded border px-2 py-1 text-xs ${directionTone(direction)}`}>{direction}</span>
      <span className="font-medium">{asset}</span>
      {size ? <span className="text-muted-foreground">{size}U</span> : null}
      {entry ? <span className="text-muted-foreground">Entry: {formatMoney(entry)}</span> : null}
      {exit ? <span className="text-muted-foreground">Exit: {formatMoney(exit)}</span> : null}
      <span className={pnl >= 0 ? "text-emerald-300" : "text-red-300"}>P&L: {pnl >= 0 ? "+" : ""}{formatMoney(pnl)}</span>
    </div>
  );
}

function EmotionChip({ label }: { label: string }) {
  const lower = label.toLowerCase();
  let tone = "bg-gray-500/20 text-gray-300 border-gray-400/20";
  let marker = "😐";
  if (/fomo|greed/.test(lower)) {
    tone = "bg-orange-500/20 text-orange-300 border-orange-400/20";
    marker = "😤";
  } else if (/overconfident/.test(lower)) {
    tone = "bg-yellow-500/20 text-yellow-300 border-yellow-400/20";
    marker = "🤑";
  } else if (/fear|panic/.test(lower)) {
    tone = "bg-blue-500/20 text-blue-300 border-blue-400/20";
    marker = "😨";
  } else if (/bored|apathetic/.test(lower)) {
    tone = "bg-purple-500/20 text-purple-300 border-purple-400/20";
    marker = "😴";
  } else if (/analytical/.test(lower)) {
    tone = "bg-cyan-500/20 text-cyan-300 border-cyan-400/20";
    marker = "🧠";
  }
  return <span className={`rounded border px-2 py-1 text-xs ${tone}`}>{marker} {label}</span>;
}

function ConfidenceBadge({ value }: { value: string }) {
  const tone = /^A/.test(value) ? "border-emerald-400/25 text-emerald-200" : /^B/.test(value) ? "border-cyan-400/25 text-cyan-200" : /^C/.test(value) ? "border-amber-400/25 text-amber-200" : "border-red-400/25 text-red-200";
  return <span className={`rounded border px-2 py-1 text-xs ${tone}`}>Confidence {value}</span>;
}

function DimensionBox({ title, value }: { title: string; value: string }) {
  return (
    <section className="rounded-md border border-white/10 p-3">
      <div className="mb-2 text-xs uppercase tracking-wide text-muted-foreground">{title}</div>
      <p className="whitespace-pre-wrap text-sm text-muted-foreground">{value}</p>
    </section>
  );
}

function parseDimensions(notes?: string | null) {
  const parsed = safeJson(notes);
  const d1 = parsed?.dimension1TradeData ?? {};
  const d2 = parsed?.dimension2Reasoning ?? {};
  const d3 = parsed?.dimension3Emotion ?? {};
  const d4 = parsed?.dimension4Reflection ?? {};
  return {
    trade: {
      source: d2.source,
      direction: d1.direction,
      asset: d1.asset,
      entryPrice: numberOrUndefined(d1.entryPrice),
      exitPrice: numberOrUndefined(d1.exitPrice),
      positionSize: numberOrUndefined(d1.positionSize),
      pnl: numberOrUndefined(d1.pnl),
      detail: Object.keys(d1).length ? JSON.stringify(d1, null, 2) : "",
    },
    reasoning: {
      confidence: d2.confidence,
      preview: d2.thesis || d2.reasoning || d2.source,
      detail: Object.keys(d2).length ? JSON.stringify(d2, null, 2) : "",
    },
    emotion: {
      label: d3.label || d3.mood,
      pressure: numberOrUndefined(d3.pressure ?? d3.pressureLevel),
    },
    reflection: {
      preview: d4.summary || d4.lesson,
      detail: Object.keys(d4).length ? JSON.stringify(d4, null, 2) : "",
    },
  };
}

function PressureBar({ value }: { value: number }) {
  const clamped = Math.max(0, Math.min(10, Math.round(value)));
  return (
    <div className="mt-3">
      <div className="mb-1 flex justify-between text-xs text-muted-foreground">
        <span>Pressure</span>
        <span>{clamped}/10</span>
      </div>
      <div className="h-1.5 rounded-full bg-white/10">
        <div className="h-full rounded-full bg-cyan-300" style={{ width: `${clamped * 10}%` }} />
      </div>
    </div>
  );
}

function pressureFromDiscipline(value?: number | null) {
  const discipline = Number(value ?? 75);
  if (!Number.isFinite(discipline)) return 5;
  return Math.max(0, Math.min(10, Math.round((100 - discipline) / 10)));
}

function safeJson(value?: string | null): any | null {
  if (!value) return null;
  try {
    const parsed = JSON.parse(value);
    return parsed && typeof parsed === "object" ? parsed : null;
  } catch {
    return null;
  }
}

function plainPreview(value?: string | null) {
  if (!value) return "";
  return value.trim().replace(/\s+/g, " ").slice(0, 260);
}

function tradeDetail(trade: JournalCardTrade | undefined, pnl: number) {
  if (!trade) return `Manual journal note\nP&L: ${formatMoney(pnl)}`;
  return `Direction: ${trade.direction ?? "n/a"}\nAsset: ${trade.asset ?? "n/a"}\nEntry: ${formatMoney(trade.entryPrice)}\nExit: ${trade.exitPrice ? formatMoney(trade.exitPrice) : "open"}\nP&L: ${formatMoney(pnl)}`;
}

function directionTone(direction: string) {
  if (direction === "LONG" || direction === "YES") return "border-emerald-400/25 bg-emerald-400/10 text-emerald-200";
  if (direction === "SHORT" || direction === "NO") return "border-red-400/25 bg-red-400/10 text-red-200";
  return "border-white/10 text-muted-foreground";
}

function numberOrUndefined(value: unknown) {
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : undefined;
}
