import type { AlphaRepo } from "./repos/alpha-repo.js";
import type { ApprovalRepo } from "./repos/approval-repo.js";
import type { ArtifactRepo } from "./repos/artifact-repo.js";
import type { AuditRepo } from "./repos/audit-repo.js";
import type { DecisionRepo } from "./repos/decision-repo.js";
import type { EvolutionRepo } from "./repos/evolution-repo.js";
import type { InfrastructureRepo } from "./repos/infrastructure-repo.js";
import type { JournalRepo } from "./repos/journal-repo.js";
import type { MemoryRepo } from "./repos/memory-repo.js";
import type { PaperTradingRepo } from "./repos/paper-trading-repo.js";
import type { ReviewRepo } from "./repos/review-repo.js";
import type { TimelineRepo } from "./repos/timeline-repo.js";
import type { WorkspaceRepo } from "./repos/workspace-repo.js";

export interface RepositoriesSurface {
  createTimeline: TimelineRepo["createTimeline"];
  createSessionFork: TimelineRepo["createSessionFork"];
  createAuditRecord: AuditRepo["createAuditRecord"];
  upsertMemory: MemoryRepo["upsertMemory"];
  writeMemory: MemoryRepo["writeMemory"];
  queryMemory: MemoryRepo["queryMemory"];
  deleteMemory: MemoryRepo["deleteMemory"];
  upsertWorkspace: WorkspaceRepo["upsertWorkspace"];
  createWorkspace: WorkspaceRepo["createWorkspace"];
  listWorkspaces: WorkspaceRepo["listWorkspaces"];
  getWorkspace: WorkspaceRepo["getWorkspace"];
  updateWorkspace: WorkspaceRepo["updateWorkspace"];
  deleteWorkspace: WorkspaceRepo["deleteWorkspace"];
  linkWorkspace: WorkspaceRepo["linkWorkspace"];
  workspaceContext: WorkspaceRepo["workspaceContext"];
  ensureDefaultWorkspace: WorkspaceRepo["ensureDefaultWorkspace"];
  createDecision: DecisionRepo["createDecision"];
  updateDecisionStatus: DecisionRepo["updateDecisionStatus"];
  listDecisions: DecisionRepo["listDecisions"];
  getDecision: DecisionRepo["getDecision"];
  createPaperOrder: PaperTradingRepo["createPaperOrder"];
  createPaperTrade: PaperTradingRepo["createPaperTrade"];
  settlePaperTrade: PaperTradingRepo["settlePaperTrade"];
  cancelPaperTrade: PaperTradingRepo["cancelPaperTrade"];
  updatePaperTrade: PaperTradingRepo["updatePaperTrade"];
  partialClosePaperTrade: PaperTradingRepo["partialClosePaperTrade"];
  listPaperTrades: PaperTradingRepo["listPaperTrades"];
  getPaperTrade: PaperTradingRepo["getPaperTrade"];
  createJournalEntry: JournalRepo["createJournalEntry"];
  attachJournalArtifact: JournalRepo["attachJournalArtifact"];
  createReview: ReviewRepo["createReview"];
  attachReviewArtifact: ReviewRepo["attachReviewArtifact"];
  listReviews: ReviewRepo["listReviews"];
  getReview: ReviewRepo["getReview"];
  reviewMetrics: ReviewRepo["reviewMetrics"];
  createArtifact: ArtifactRepo["createArtifact"];
  getArtifact: ArtifactRepo["getArtifact"];
  createApproval: ApprovalRepo["createApproval"];
  updateApprovalStatus: ApprovalRepo["updateApprovalStatus"];
  createEvolutionProposal: EvolutionRepo["createEvolutionProposal"];
  createEvolutionSuggestion: EvolutionRepo["createEvolutionSuggestion"];
  listEvolutionSuggestions: EvolutionRepo["listEvolutionSuggestions"];
  getEvolutionSuggestion: EvolutionRepo["getEvolutionSuggestion"];
  updateEvolutionSuggestionStatus: EvolutionRepo["updateEvolutionSuggestionStatus"];
  createResearchSession: AlphaRepo["createResearchSession"];
  updateResearchSession: AlphaRepo["updateResearchSession"];
  listResearchSessions: AlphaRepo["listResearchSessions"];
  getResearchSession: AlphaRepo["getResearchSession"];
  upsertStrategy: AlphaRepo["upsertStrategy"];
  createBacktest: AlphaRepo["createBacktest"];
  portfolioSnapshot: AlphaRepo["portfolioSnapshot"];
  upsertMarketPrice: AlphaRepo["upsertMarketPrice"];
  getLatestMarketPrice: AlphaRepo["getLatestMarketPrice"];
  listMarketPrices: AlphaRepo["listMarketPrices"];
  upsertOhlcvCandles: AlphaRepo["upsertOhlcvCandles"];
  getOhlcvCandles: AlphaRepo["getOhlcvCandles"];
  getCachedSearchResults: AlphaRepo["getCachedSearchResults"];
  cacheSearchResults: AlphaRepo["cacheSearchResults"];
  list: InfrastructureRepo["list"];
  upsertSkill: InfrastructureRepo["upsertSkill"];
  upsertWorkflow: InfrastructureRepo["upsertWorkflow"];
  createWorkflowRun: InfrastructureRepo["createWorkflowRun"];
  finishWorkflowRun: InfrastructureRepo["finishWorkflowRun"];
  createSkillRun: InfrastructureRepo["createSkillRun"];
  finishSkillRun: InfrastructureRepo["finishSkillRun"];
  createPlan: InfrastructureRepo["createPlan"];
  updatePlanStatus: InfrastructureRepo["updatePlanStatus"];
  listPlans: InfrastructureRepo["listPlans"];
  getPlan: InfrastructureRepo["getPlan"];
  setCache: InfrastructureRepo["setCache"];
  getCache: InfrastructureRepo["getCache"];
  upsertMcpServer: InfrastructureRepo["upsertMcpServer"];
  createMcpDiscovery: InfrastructureRepo["createMcpDiscovery"];
  updateMcpServer: InfrastructureRepo["updateMcpServer"];
  upsertMcpPermission: InfrastructureRepo["upsertMcpPermission"];
  createBrowserSession: InfrastructureRepo["createBrowserSession"];
  upsertMarketplaceItem: InfrastructureRepo["upsertMarketplaceItem"];
}